version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
